#!/bin/bash
if [ $# -ne 2 ]; then
	echo "Error, you have not given 2 parameters";
	exit 1;
fi

if [ -f "$1" ]; then
	echo "$1 is a file in the current directory";
else
	echo "there is no file $1 in the current directory";
fi

if [ -d "$2" ]; then

	echo "$2 is a directory in the current directory";
else
	echo "there is no directory called $2 in the current directory";
fi



